/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Entity.Customer;
import Repository.CustomerRepository;

/**
 *
 * @author juanc
 */
public class agregarCliente extends javax.swing.JFrame {

    static CustomerRepository cr;
    private Customer c = new Customer();
    
    /**
     * Creates new form agregarCliente
     */
    public agregarCliente(CustomerRepository cr) {
        initComponents();
        this.cr = cr;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        areaPhone = new javax.swing.JTextField();
        areaAddress = new javax.swing.JTextField();
        areaRFC = new javax.swing.JTextField();
        areaName = new javax.swing.JTextField();
        bGuardarCliente = new javax.swing.JButton();
        bCanelar = new javax.swing.JButton();
        bGuardarCliente1 = new javax.swing.JButton();
        bCanelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 210, 50);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 80, 16);

        jLabel3.setText("RFC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 60, 16);

        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 240, 80, 16);

        jLabel5.setText("Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 300, 50, 16);

        areaPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(areaPhone);
        areaPhone.setBounds(110, 300, 710, 22);

        areaAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaAddressActionPerformed(evt);
            }
        });
        getContentPane().add(areaAddress);
        areaAddress.setBounds(110, 240, 710, 22);

        areaRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaRFCActionPerformed(evt);
            }
        });
        getContentPane().add(areaRFC);
        areaRFC.setBounds(110, 180, 710, 22);

        areaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaNameActionPerformed(evt);
            }
        });
        getContentPane().add(areaName);
        areaName.setBounds(110, 120, 710, 22);

        bGuardarCliente.setText("Guardar");
        bGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardarCliente);
        bGuardarCliente.setBounds(60, 430, 90, 25);

        bCanelar.setText("Cancelar");
        bCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCanelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCanelar);
        bCanelar.setBounds(689, 430, 100, 25);

        bGuardarCliente1.setText("Guardar");
        bGuardarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardarCliente1);
        bGuardarCliente1.setBounds(60, 430, 90, 25);

        bCanelar1.setText("Cancelar");
        bCanelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCanelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bCanelar1);
        bCanelar1.setBounds(689, 430, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaPhoneActionPerformed

    private void areaAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaAddressActionPerformed

    private void areaRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaRFCActionPerformed

    private void areaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaNameActionPerformed

    private void bCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCanelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCanelarActionPerformed

    private void bGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarClienteActionPerformed
        c.setName(areaName.getText());
        c.setRfc(areaRFC.getText());
        c.setAddress(areaAddress.getText());
        c.setPhone(areaPhone.getText());
        
        cr.create(c);
        
        Clientes vc = new Clientes(cr);
        vc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bGuardarClienteActionPerformed

    private void bGuardarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bGuardarCliente1ActionPerformed

    private void bCanelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCanelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCanelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarCliente(cr).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaAddress;
    private javax.swing.JTextField areaName;
    private javax.swing.JTextField areaPhone;
    private javax.swing.JTextField areaRFC;
    private javax.swing.JButton bCanelar;
    private javax.swing.JButton bCanelar1;
    private javax.swing.JButton bGuardarCliente;
    private javax.swing.JButton bGuardarCliente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
