/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Entity.Product;
import Entity.Sale;
import Entity.Saleitem;
import Repository.CustomerRepository;
import Repository.ProductRepository;
import Repository.SaleItemRepository;
import Repository.SaleRepository;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author juanc
 */
public class agregarProductoCarrito extends javax.swing.JFrame {

    Saleitem si = new Saleitem();
    static JFrame ventanaPadre;
    static ProductRepository productR;
    static CustomerRepository customerR;
    static SaleItemRepository saleItemR;
    static SaleRepository saleR;
    static  Sale s;

    /**
     * Creates new form agregarProductoCarrito
     */
    public agregarProductoCarrito(JFrame ventanaPadre, ProductRepository pr, CustomerRepository cr, SaleRepository sr, Sale s) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventanaPadre = ventanaPadre;
        this.productR = pr;
        this.saleItemR = saleItemR;
        this.customerR = cr;
        this.saleR = sr;
        this.s = s;        
        listar();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void listar() {
        List<Product> lp = productR.findProductEntities();

        for (int i = 0; i < lp.size(); i++) {
            seleccionProducto.addItem(lp.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seleccionProducto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        areaCantidad = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 310));
        setMinimumSize(new java.awt.Dimension(420, 310));
        setPreferredSize(new java.awt.Dimension(420, 310));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Seleccionar Producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 140, 16);

        seleccionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionProductoActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionProducto);
        seleccionProducto.setBounds(10, 50, 380, 22);

        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 60, 16);
        getContentPane().add(areaCantidad);
        areaCantidad.setBounds(10, 140, 70, 22);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar);
        bCancelar.setBounds(269, 230, 100, 25);

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar);
        bAgregar.setBounds(30, 230, 120, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
                        
        si.setProductID((Product) seleccionProducto.getSelectedItem());
        si.setPrice((Product) seleccionProducto.getSelectedItem());
        si.setQuantity(Integer.parseInt(areaCantidad.getText()));
        si.setTotal();
        si.setSaleID(s);
        
        System.out.println(si.getProductID());
        
                
        saleItemR.create(si);

        realizarCompra rc = new realizarCompra(saleR, saleItemR, customerR, productR);
        this.dispose();
        ventanaPadre.dispose();



    }//GEN-LAST:event_bAgregarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void seleccionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarProductoCarrito(ventanaPadre, productR, customerR, saleR, s).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaCantidad;
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox seleccionProducto;
    // End of variables declaration//GEN-END:variables
}
