/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Entity.Category;
import Repository.CategoryRepository;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanc
 */
public class Categorias extends javax.swing.JFrame {

    static CategoryRepository cr;
    
    /**
     * Creates new form Categorias
     */
    public Categorias(CategoryRepository cr) {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla();
        this.cr = cr;
        llenarTabla();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void llenarTabla() {
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        List<Category> lc = cr.findCategoryEntities();
        Object o[] = null;

        for (int i = 0; i < lc.size(); i++) {
            modelo.addRow(o);
            modelo.setValueAt(lc.get(i).getId(), i, 0);
            modelo.setValueAt(lc.get(i).getName(), i, 1);
            modelo.setValueAt(lc.get(i).getDescription(), i, 2);           
        }
        
        for (int i = 0; i < tCategorias.getColumnCount(); i++) {
            tCategorias.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    DefaultTableModel modelo;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

    private void modeloTabla() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "ID", "Name",
                        "Description"}) {
                        Class[] types = new Class[]{
                            java.lang.Integer.class,
                            java.lang.String.class,
                            java.lang.String.class
                        };
                        boolean[] canEdit = new boolean[]{
                            false, false, false
                        };

                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types[columnIndex];
                        }

                        @Override
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                            return canEdit[colIndex];
                        }
                    });
            tCategorias.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }

        tCategorias.getColumnModel().getColumn(0).setPreferredWidth(80);
        tCategorias.getColumnModel().getColumn(0).setMaxWidth(80);
        tCategorias.getColumnModel().getColumn(1).setPreferredWidth(150);
        tCategorias.getColumnModel().getColumn(1).setMaxWidth(150);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tCategorias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bAgregarCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        tCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tCategorias);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 900, 460);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 20, 70, 16);

        bAgregarCategoria.setText("Agregar Categoría");
        bAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregarCategoria);
        bAgregarCategoria.setBounds(50, 520, 150, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarCategoriaActionPerformed
        agregarCategoria ac = new agregarCategoria(cr);
        ac.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bAgregarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias(cr).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCategorias;
    // End of variables declaration//GEN-END:variables
}
