/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Repository.CategoryRepository;
import Repository.CustomerRepository;
import Repository.ProductRepository;
import Repository.ProviderRepository;
import Repository.SaleItemRepository;
import Repository.SaleRepository;

/**
 *
 * @author juanc
 */
public class Principal extends javax.swing.JFrame {

    final CategoryRepository categoryR = new CategoryRepository();
    final CustomerRepository customerR = new CustomerRepository();
    final ProductRepository productR = new ProductRepository();
    final ProviderRepository providerR = new ProviderRepository();
    final SaleItemRepository saleItemR = new SaleItemRepository();
    final SaleRepository saleR = new SaleRepository();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bProveedores = new javax.swing.JButton();
        bClientes = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        bProveedores.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bProveedores.setText("Proveedores");
        bProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(bProveedores);
        bProveedores.setBounds(660, 210, 170, 100);

        bClientes.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bClientes.setText("Clientes");
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });
        getContentPane().add(bClientes);
        bClientes.setBounds(370, 210, 170, 100);

        bProductos.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bProductos.setText("Productos");
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        getContentPane().add(bProductos);
        bProductos.setBounds(70, 210, 170, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedoresActionPerformed
        Proveedores p = new Proveedores(providerR);
        p.setVisible(true);
    }//GEN-LAST:event_bProveedoresActionPerformed

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        Clientes c = new Clientes(customerR);
        c.setVisible(true);
    }//GEN-LAST:event_bClientesActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        Productos p = new Productos(productR, categoryR, providerR);
        p.setVisible(true);
    }//GEN-LAST:event_bProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bProductos;
    private javax.swing.JButton bProveedores;
    // End of variables declaration//GEN-END:variables
}
