/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Repository.CategoryRepository;
import Repository.CustomerRepository;
import Repository.ProductRepository;
import Repository.ProviderRepository;
import Repository.SaleItemRepository;
import Repository.SaleRepository;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author juanc
 */
public class Principal extends javax.swing.JFrame {

    final EntityManagerFactory emf = Persistence.createEntityManagerFactory("SistemaVentasPU");
    final CategoryRepository categoryR = new CategoryRepository(emf);
    final CustomerRepository customerR = new CustomerRepository(emf);
    final ProductRepository productR = new ProductRepository(emf);
    final ProviderRepository providerR = new ProviderRepository(emf);
    final SaleItemRepository saleItemR = new SaleItemRepository(emf);
    final SaleRepository saleR = new SaleRepository(emf);
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCompras = new javax.swing.JButton();
        bClientes = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();
        bProveedores1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        bCompras.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bCompras.setText("Realizar compra");
        bCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprasActionPerformed(evt);
            }
        });
        getContentPane().add(bCompras);
        bCompras.setBounds(690, 210, 170, 100);

        bClientes.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bClientes.setText("Clientes");
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });
        getContentPane().add(bClientes);
        bClientes.setBounds(250, 210, 170, 100);

        bProductos.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bProductos.setText("Productos");
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        getContentPane().add(bProductos);
        bProductos.setBounds(40, 210, 170, 100);

        bProveedores1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        bProveedores1.setText("Proveedores");
        bProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedores1ActionPerformed(evt);
            }
        });
        getContentPane().add(bProveedores1);
        bProveedores1.setBounds(470, 210, 170, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprasActionPerformed
        realizarCompra rc = new realizarCompra(saleR, saleItemR, customerR, productR);
        rc.setVisible(true);
    }//GEN-LAST:event_bComprasActionPerformed

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        Clientes c = new Clientes(customerR);
        c.setVisible(true);
    }//GEN-LAST:event_bClientesActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        Productos p = new Productos(productR, categoryR, providerR);
        p.setVisible(true);
    }//GEN-LAST:event_bProductosActionPerformed

    private void bProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedores1ActionPerformed
        Proveedores p = new Proveedores(providerR);
        p.setVisible(true);
    }//GEN-LAST:event_bProveedores1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bCompras;
    private javax.swing.JButton bProductos;
    private javax.swing.JButton bProveedores1;
    // End of variables declaration//GEN-END:variables
}
