/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Entity.Provider;
import Repository.ProviderRepository;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanc
 */
public class Proveedores extends javax.swing.JFrame {

    static ProviderRepository providerR;
    /**
     * Creates new form Proveedores
     */
    public Proveedores(ProviderRepository pr) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.providerR = pr;
        modeloTabla();
        llenarTabla();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void llenarTabla() {
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        List<Provider> lp = providerR.findProviderEntities();
        Object o[] = null;

        for (int i = 0; i < lp.size(); i++) {
            modelo.addRow(o);
            modelo.setValueAt(lp.get(i).getId(), i, 0);      
            modelo.setValueAt(lp.get(i).getName(), i, 1);
            modelo.setValueAt(lp.get(i).getAddress(), i, 2);
            modelo.setValueAt(lp.get(i).getPhone(), i, 3);
            modelo.setValueAt(lp.get(i).getWebsite(), i, 4);
        }
        
        for (int i = 0; i < tProveedores.getColumnCount(); i++) {
            tProveedores.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    DefaultTableModel modelo;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();   

    private void modeloTabla() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "ID", "Name",
                        "Address", "Phone", "Website"}) {
                        Class[] types = new Class[]{
                            java.lang.Integer.class,
                            java.lang.String.class,
                            java.lang.String.class,
                            java.lang.String.class,
                            java.lang.String.class
                        };
                        boolean[] canEdit = new boolean[]{
                            false, false, false, false, false
                        };

                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types[columnIndex];
                        }

                        @Override
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                            return canEdit[colIndex];
                        }
                    });
            tProveedores.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
        tProveedores.getColumnModel().getColumn(0).setPreferredWidth(80);
        tProveedores.getColumnModel().getColumn(0).setMaxWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bAgregarProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        tProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tProveedores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 900, 460);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Providers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 20, 100, 16);

        bAgregarProveedor.setText("Agregar Proveedor");
        bAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregarProveedor);
        bAgregarProveedor.setBounds(50, 520, 160, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProveedoresMouseClicked
        int selectedRow = tProveedores.getSelectedRow();        
        int id = (int) modelo.getValueAt(selectedRow, 0);
        
        Provider p = providerR.findProvider(id);
        
        mostrarProveedor mp = new mostrarProveedor(providerR, p);
        mp.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_tProveedoresMouseClicked

    private void bAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarProveedorActionPerformed
        agregarProveedor ap = new agregarProveedor(providerR);
        ap.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bAgregarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores(providerR).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tProveedores;
    // End of variables declaration//GEN-END:variables
}
