/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Entity.Customer;
import Entity.Sale;
import Entity.Saleitem;
import Repository.CustomerRepository;
import Repository.ProductRepository;
import Repository.SaleItemRepository;
import Repository.SaleRepository;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanc
 */
public class realizarCompra extends javax.swing.JFrame {

    static SaleItemRepository saleItemR;
    static SaleRepository saleR;
    static CustomerRepository customerR;
    static ProductRepository productR;
    final Sale s;
    
    /**
     * Creates new form realizarCompra
     */
    public realizarCompra(SaleRepository sr, SaleItemRepository sir, CustomerRepository cr, ProductRepository pr) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.saleItemR = sir;
        this.saleR = sr;  
        this.customerR = cr;
        this.productR = pr;
        listar();        
        llenarTabla();
        s = new Sale();
        sr.create(s);       
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
    }
    
    public void listar(){        
        List<Customer> lc = customerR.findCustomerEntities();
               
        for (int i = 0; i < lc.size(); i++) {
            listaClientes.addItem(lc.get(i));
        }
    }
    
    public void llenarTabla() {
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        List<Saleitem> ls = saleItemR.findSaleitemEntities();
        Object o[] = null;

        for (int i = 0; i < ls.size(); i++) {
            modelo.addRow(o);
            modelo.setValueAt(ls.get(i).getId(), i, 0);      
            modelo.setValueAt(ls.get(i).getProductID(), i, 1);            
            modelo.setValueAt(ls.get(i).getPrice(), i, 3);
            modelo.setValueAt(ls.get(i).getQuantity(), i, 4);
            modelo.setValueAt(ls.get(i).getTotal(), i, 5);
        }
        
        for (int i = 0; i < tProductos.getColumnCount(); i++) {
            tProductos.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    DefaultTableModel modelo;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();   

    private void modeloTabla() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "ID", "Product ID",
                        "Price", "Quantity", "Total"}) {
                        Class[] types = new Class[]{
                            java.lang.Integer.class,                            
                            java.lang.Integer.class,
                            java.lang.Float.class,
                            java.lang.Integer.class,
                            java.lang.Float.class,                            
                        };
                        boolean[] canEdit = new boolean[]{
                            false, false, false, false, false
                        };

                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types[columnIndex];
                        }

                        @Override
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                            return canEdit[colIndex];
                        }
                    });
            tProductos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
        tProductos.getColumnModel().getColumn(0).setPreferredWidth(80);
        tProductos.getColumnModel().getColumn(0).setMaxWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listaClientes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        bAgregarProducto = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bRealizarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Realizar compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 220, 50);

        jLabel2.setText("Seleccionar cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 120, 16);

        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });
        getContentPane().add(listaClientes);
        listaClientes.setBounds(50, 150, 360, 22);

        jLabel3.setText("Carrito de compras");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 120, 120, 16);

        tProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 150, 440, 350);

        bAgregarProducto.setText("Agregar Producto");
        bAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregarProducto);
        bAgregarProducto.setBounds(600, 510, 150, 25);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar);
        bCancelar.setBounds(260, 230, 130, 40);

        bRealizarCompra.setText("Realizar compra");
        getContentPane().add(bRealizarCompra);
        bRealizarCompra.setBounds(70, 230, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarProductoActionPerformed
        agregarProductoCarrito apc = new agregarProductoCarrito(this, productR, customerR, saleR, s);
        apc.setVisible(true);
                
    }//GEN-LAST:event_bAgregarProductoActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaClientesActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(realizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(realizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(realizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new realizarCompra(saleR, saleItemR, customerR, productR).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarProducto;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bRealizarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listaClientes;
    private javax.swing.JTable tProductos;
    // End of variables declaration//GEN-END:variables
}
